# Formules de maths, 1re partie : (titre, formule LaTeX, legende separee par |)
CAT=["Calcul","Equations","Fonctions","Suites et sommes"]
F=[[
("Identite remarquable 1",r"(a+b)^2=a^2+2ab+b^2","Carre d'une somme"),
("Identite remarquable 2",r"(a-b)^2=a^2-2ab+b^2","Carre d'une difference"),
("Identite remarquable 3",r"(a+b)(a-b)=a^2-b^2","Produit d'une somme par une difference"),
("Double distributivite",r"(a+b)(c+d)=ac+ad+bc+bd","Chaque terme de la 1re parenthese|multiplie chaque terme de la 2e"),
("Produit de puissances",r"a^n\times a^m=a^{n+m}","On ajoute les exposants"),
("Quotient de puissances",r"\frac{a^n}{a^m}=a^{n-m}","On soustrait les exposants (a non nul)"),
("Puissance de puissance",r"(a^n)^m=a^{n\times m}","On multiplie les exposants"),
("Exposant negatif",r"a^{-n}=\frac{1}{a^n}","a non nul|a^0 = 1"),
("Produit de racines",r"\sqrt{a\times b}=\sqrt{a}\times\sqrt{b}","a et b positifs|Attention : faux pour une somme"),
("Quotient de racines",r"\sqrt{\frac{a}{b}}=\frac{\sqrt{a}}{\sqrt{b}}","a positif, b strictement positif"),
("Somme de fractions",r"\frac{a}{b}+\frac{c}{d}=\frac{ad+bc}{bd}","On met au meme denominateur"),
("Produit de fractions",r"\frac{a}{b}\times\frac{c}{d}=\frac{ac}{bd}","Numerateurs entre eux, denominateurs entre eux"),
("Quotient de fractions",r"\frac{a}{b}:\frac{c}{d}=\frac{a}{b}\times\frac{d}{c}","Diviser, c'est multiplier par l'inverse"),
("Taux d'evolution",r"t=\frac{V_A-V_D}{V_D}","VD : valeur de depart|VA : valeur d'arrivee|x 100 pour l'avoir en pourcentage"),
("Coefficient multiplicateur",r"CM=1+\frac{t}{100}","t : evolution en % (negatif si baisse)|Hausse de 20 % : CM = 1,2|Baisse de 20 % : CM = 0,8"),
],[
("Equation du 1er degre",r"ax+b=0   x=-\frac{b}{a}","a non nul"),
("Equation produit nul",r"A\times B=0","Un produit est nul si et seulement si|l'un des facteurs est nul : A = 0 ou B = 0"),
("Equation x^2 = a",r"x=\sqrt{a}   x=-\sqrt{a}","Si a > 0 : deux solutions|Si a = 0 : x = 0|Si a < 0 : pas de solution"),
("Discriminant",r"\Delta=b^2-4ac","Pour ax^2 + bx + c = 0 (a non nul)|Delta > 0 : 2 solutions   Delta = 0 : 1 solution|Delta < 0 : pas de solution reelle"),
("Solutions (Delta > 0)",r"x=\frac{-b\pm\sqrt{\Delta}}{2a}","Deux solutions : une avec +, une avec -"),
("Solution double (Delta = 0)",r"x_0=-\frac{b}{2a}","Une seule solution"),
("Somme et produit des racines",r"x_1+x_2=-\frac{b}{a}   x_1 x_2=\frac{c}{a}","Pratique pour verifier ses solutions"),
("Forme factorisee",r"a(x-x_1)(x-x_2)","x1 et x2 : les deux racines|Si Delta = 0 : a(x - x0)^2"),
("Forme canonique",r"a(x-\alpha)^2+f(\alpha)","alpha = -b / 2a|Sommet de la parabole : S(alpha ; f(alpha))"),
("Inequations",r"a<b   -a>-b","Multiplier ou diviser par un nombre negatif|change le sens de l'inegalite"),
],[
("Fonction affine",r"f(x)=mx+p","m : coefficient directeur (pente)|p : ordonnee a l'origine|m > 0 : croissante   m < 0 : decroissante"),
("Coefficient directeur",r"m=\frac{y_B-y_A}{x_B-x_A}","Droite passant par A et B (xA different de xB)"),
("Taux de variation",r"\frac{f(b)-f(a)}{b-a}","Entre a et b|C'est la pente de la secante"),
("Nombre derive",r"f'(a)=lim \frac{f(a+h)-f(a)}{h}","Limite quand h tend vers 0|C'est la pente de la tangente en a"),
("Equation de la tangente",r"y=f'(a)(x-a)+f(a)","Tangente a la courbe au point d'abscisse a"),
("Derivee d'une puissance",r"(x^n)'=n x^{n-1}","Exemples : (x^2)' = 2x   (x^3)' = 3x^2|La derivee d'une constante est 0"),
("Derivee de l'inverse",r"(\frac{1}{x})'=-\frac{1}{x^2}","x non nul"),
("Derivee de la racine",r"(\sqrt{x})'=\frac{1}{2\sqrt{x}}","x strictement positif"),
("Derivee d'un produit",r"(uv)'=u'v+uv'",""),
("Derivee d'un quotient",r"(\frac{u}{v})'=\frac{u'v-uv'}{v^2}","v ne s'annule pas"),
("Signe de la derivee",r"f'(x)\geq 0","f' positive : f croissante|f' negative : f decroissante|f' s'annule en changeant de signe : extremum"),
("Exponentielle",r"e^{a+b}=e^a\times e^b","e^0 = 1   e^(-a) = 1 / e^a|(e^x)' = e^x|e^x > 0 pour tout x"),
],[
("Suite arithmetique",r"u_{n+1}=u_n+r","r : raison|On ajoute toujours le meme nombre"),
("Terme general (arithmetique)",r"u_n=u_0+n\times r","Ou : un = up + (n - p) x r"),
("Suite geometrique",r"u_{n+1}=q\times u_n","q : raison|On multiplie toujours par le meme nombre"),
("Terme general (geometrique)",r"u_n=u_0\times q^n","Ou : un = up x q^(n - p)"),
("Notation sigma",r"\Sigma_{i=1}^{n} x_i=x_1+x_2+...+x_n","Somme des xi pour i allant de 1 a n"),
("Somme des entiers",r"1+2+...+n=\frac{n(n+1)}{2}","Exemple : 1 + 2 + ... + 100 = 5050"),
("Somme des carres",r"1^2+2^2+...+n^2=\frac{n(n+1)(2n+1)}{6}",""),
("Somme des cubes",r"1^3+2^3+...+n^3=(\frac{n(n+1)}{2})^2",""),
("Somme des impairs",r"1+3+5+...+(2n-1)=n^2","Somme des n premiers nombres impairs"),
("Somme arithmetique",r"S=(n+1)\times\frac{u_0+u_n}{2}","Somme de u0 a un|Nombre de termes x moyenne du premier|et du dernier terme"),
("Somme geometrique",r"1+q+q^2+...+q^n=\frac{1-q^{n+1}}{1-q}","q different de 1|Multiplier par u0 pour la somme de u0 a un"),
("Sens de variation",r"u_{n+1}-u_n","Positif pour tout n : suite croissante|Negatif pour tout n : suite decroissante"),
]]
