# Formules de maths, 2e partie : (titre, formule LaTeX, legende separee par |)
CAT=["Statistiques","Probabilites","Geometrie","Vecteurs et reperes","Trigonometrie"]
F=[[
("Moyenne",r"\bar{x}=\frac{x_1+x_2+...+x_N}{N}","Somme des valeurs divisee par l'effectif total N"),
("Moyenne (notation sigma)",r"\bar{x}=\frac{1}{N}\Sigma_{i=1}^{N} x_i",""),
("Moyenne ponderee",r"\bar{x}=\frac{n_1 x_1+n_2 x_2+...+n_p x_p}{n_1+n_2+...+n_p}","ni : effectif (ou coefficient) de la valeur xi"),
("Frequence",r"f=\frac{effectif}{effectif total}","Nombre entre 0 et 1|La somme des frequences vaut 1"),
("Variance",r"V=\frac{(x_1-\bar{x})^2+...+(x_N-\bar{x})^2}{N}","Moyenne des carres des ecarts a la moyenne"),
("Variance (autre formule)",r"V=\frac{x_1^2+x_2^2+...+x_N^2}{N}-\bar{x}^2","Moyenne des carres moins carre de la moyenne"),
("Ecart type",r"\sigma=\sqrt{V}","Racine carree de la variance|Mesure la dispersion autour de la moyenne|Meme unite que les valeurs"),
("Mediane",r"Me","Valeur qui partage la serie triee en deux|N impair : la valeur du milieu|N pair : moyenne des deux valeurs du milieu"),
("Quartiles",r"Q_1   Q_3","Q1 : plus petite valeur telle qu'au moins 25 %|des valeurs lui sont inferieures ou egales|Q3 : pareil avec 75 %"),
("Ecart interquartile",r"Q_3-Q_1","Contient au moins la moitie des valeurs|Peu sensible aux valeurs extremes"),
("Etendue",r"e=x_{max}-x_{min}","Plus grande valeur moins plus petite valeur"),
("Linearite de la moyenne",r"\bar{ax+b}=a\bar{x}+b","Si on multiplie les valeurs par a et qu'on|ajoute b, la moyenne subit la meme chose|L'ecart type est multiplie par la valeur absolue de a"),
],[
("Equiprobabilite",r"P(A)=\frac{cas favorables}{cas possibles}","Quand toutes les issues ont la meme chance"),
("Evenement contraire",r"P(\bar{A})=1-P(A)","0 <= P(A) <= 1"),
("Union",r"P(A\cup B)=P(A)+P(B)-P(A\cap B)","A ou B|Si A et B incompatibles : P(A) + P(B)"),
("Probabilite conditionnelle",r"P_A(B)=\frac{P(A\cap B)}{P(A)}","Probabilite de B sachant A|P(A) non nulle"),
("Intersection",r"P(A\cap B)=P(A)\times P_A(B)","Sur un arbre : on multiplie le long|des branches"),
("Independance",r"P(A\cap B)=P(A)\times P(B)","A et B independants|Equivaut a : PA(B) = P(B)"),
("Probabilites totales",r"P(B)=P(A\cap B)+P(\bar{A}\cap B)","Sur un arbre : on ajoute les chemins|qui menent a B"),
("Esperance",r"E(X)=x_1 p_1+x_2 p_2+...+x_n p_n","Valeur moyenne de X sur un grand nombre|de repetitions"),
("Variance de X",r"V(X)=E(X^2)-E(X)^2","Ecart type : racine carree de V(X)"),
("Loi binomiale",r"E(X)=n\times p","n repetitions independantes|p : probabilite du succes|V(X) = n p (1 - p)"),
],[
("Theoreme de Pythagore",r"BC^2=AB^2+AC^2","Triangle ABC rectangle en A|BC : hypotenuse|Reciproque : prouve qu'il est rectangle"),
("Theoreme de Thales",r"\frac{AM}{AB}=\frac{AN}{AC}=\frac{MN}{BC}","M sur (AB), N sur (AC)|(MN) parallele a (BC)"),
("Perimetre du cercle",r"P=2\times\pi\times r","r : rayon"),
("Aire du disque",r"A=\pi\times r^2","r : rayon"),
("Aire du triangle",r"A=\frac{b\times h}{2}","b : base   h : hauteur associee"),
("Aire du trapeze",r"A=\frac{(B+b)\times h}{2}","B : grande base   b : petite base|h : hauteur"),
("Aire du parallelogramme",r"A=b\times h","b : base   h : hauteur associee|Rectangle : L x l   Carre : c x c"),
("Volume du pave",r"V=L\times l\times h","Cube : c x c x c"),
("Volume du cylindre",r"V=\pi\times r^2\times h","Prisme : aire de la base x hauteur"),
("Volume du cone",r"V=\frac{1}{3}\times B\times h","B : aire de la base   h : hauteur|Valable aussi pour la pyramide"),
("Volume de la boule",r"V=\frac{4}{3}\times\pi\times r^3",""),
("Aire de la sphere",r"A=4\times\pi\times r^2",""),
("Agrandissement",r"k   k^2   k^3","Longueurs multipliees par k|Aires multipliees par k^2|Volumes multiplies par k^3"),
],[
("Coordonnees d'un vecteur",r"\vec{AB}(x_B-x_A ; y_B-y_A)","Arrivee moins depart"),
("Relation de Chasles",r"\vec{AB}+\vec{BC}=\vec{AC}",""),
("Milieu d'un segment",r"(\frac{x_A+x_B}{2} ; \frac{y_A+y_B}{2})","Coordonnees du milieu de [AB]"),
("Distance",r"AB=\sqrt{(x_B-x_A)^2+(y_B-y_A)^2}","Dans un repere orthonorme"),
("Norme d'un vecteur",r"||\vec{u}||=\sqrt{x^2+y^2}","Pour u(x ; y) dans un repere orthonorme"),
("Determinant",r"det(\vec{u},\vec{v})=xy'-x'y","u(x ; y) et v(x' ; y')|det = 0 : vecteurs colineaires|(droites paralleles ou points alignes)"),
("Produit scalaire",r"\vec{u}\cdot\vec{v}=xx'+yy'","Dans un repere orthonorme|Nul : vecteurs orthogonaux"),
("Produit scalaire (angle)",r"\vec{u}\cdot\vec{v}=||\vec{u}||\times||\vec{v}||\times cos\theta","theta : angle entre u et v"),
("Equation reduite",r"y=mx+p","m : coefficient directeur|p : ordonnee a l'origine|Droite verticale : x = k"),
("Equation cartesienne",r"ax+by+c=0","Vecteur directeur : u(-b ; a)|Vecteur normal : n(a ; b)"),
("Equation de cercle",r"(x-a)^2+(y-b)^2=r^2","Centre (a ; b), rayon r"),
],[
("Cosinus",r"cos\alpha=\frac{adjacent}{hypotenuse}","Dans un triangle rectangle"),
("Sinus",r"sin\alpha=\frac{oppose}{hypotenuse}","Dans un triangle rectangle"),
("Tangente",r"tan\alpha=\frac{oppose}{adjacent}","Dans un triangle rectangle"),
("Relation fondamentale",r"cos^2 x+sin^2 x=1","Vraie pour tout x"),
("Tangente",r"tan x=\frac{sin x}{cos x}","cos x non nul"),
("Degres et radians",r"\pi rad=180 deg","Un tour complet : 2 pi rad = 360 deg|x deg = x pi / 180 rad"),
("Angles associes",r"cos(-x)=cos x   sin(-x)=-sin x","cos(pi - x) = -cos x   sin(pi - x) = sin x|cos(pi/2 - x) = sin x   sin(pi/2 - x) = cos x"),
("Longueur d'un arc",r"L=r\times\theta","r : rayon   theta : angle en radians"),
("Al-Kashi",r"a^2=b^2+c^2-2bc\times cos A","Triangle quelconque|a : cote oppose a l'angle A"),
("Loi des sinus",r"\frac{a}{sin A}=\frac{b}{sin B}=\frac{c}{sin C}","Triangle quelconque"),
("Aire d'un triangle",r"A=\frac{1}{2}\times b\times c\times sin A","Avec deux cotes et l'angle entre eux"),
]]
