# Formules : (categorie, titre, formule LaTeX, legende separee par |)
CAT=["Mecanique","Energie","Electricite","Ondes et optique","Chimie"]
F=[
(0,"Vitesse moyenne",r"v=\frac{d}{\Delta t}","v : vitesse (m/s)|d : distance (m)|Delta t : duree (s)"),
(0,"Poids",r"P=m\times g","P : poids (N)|m : masse (kg)|g = 9,81 N/kg"),
(0,"Gravitation universelle",r"F=G\frac{m_A m_B}{d^2}","F : force (N)|m : masses (kg)  d : distance (m)|G = 6,67.10^-11 N.m2/kg2"),
(0,"2e loi de Newton",r"\Sigma\vec{F}=m\vec{a}","Somme des forces (N)|m : masse (kg)|a : acceleration (m/s2)"),
(0,"Quantite de mouvement",r"\vec{p}=m\vec{v}","p : quantite de mouvement (kg.m/s)|m : masse (kg)|v : vitesse (m/s)"),
(0,"Pression",r"P=\frac{F}{S}","P : pression (Pa)|F : force (N)|S : surface (m2)"),
(0,"Masse volumique",r"\rho=\frac{m}{V}","rho : masse volumique (kg/m3)|m : masse (kg)|V : volume (m3)"),
(1,"Energie cinetique",r"E_c=\frac{1}{2}m v^2","Ec : energie cinetique (J)|m : masse (kg)|v : vitesse (m/s)"),
(1,"Energie potentielle",r"E_{pp}=m g z","Epp : energie potentielle (J)|m : masse (kg)  g = 9,81 N/kg|z : altitude (m)"),
(1,"Energie mecanique",r"E_m=E_c+E_{pp}","Em : energie mecanique (J)|Se conserve sans frottements"),
(1,"Travail d'une force",r"W=F\times AB\times cos\alpha","W : travail (J)|F : force (N)  AB : deplacement (m)|alpha : angle entre F et AB"),
(1,"Puissance",r"P=\frac{E}{\Delta t}","P : puissance (W)|E : energie (J)|Delta t : duree (s)"),
(1,"Rendement",r"\eta=\frac{E_{utile}}{E_{recue}}","eta : rendement (sans unite)|Toujours inferieur a 1"),
(1,"Energie thermique",r"Q=m c\Delta T","Q : energie (J)|m : masse (kg)  c : capacite (J/kg/K)|Delta T : variation de temperature"),
(2,"Loi d'Ohm",r"U=R\times I","U : tension (V)|R : resistance (Ohm)|I : intensite (A)"),
(2,"Puissance electrique",r"P=U\times I","P : puissance (W)|U : tension (V)|I : intensite (A)"),
(2,"Effet Joule",r"P=R I^2","P : puissance dissipee (W)|R : resistance (Ohm)|I : intensite (A)"),
(2,"Energie electrique",r"E=P\times\Delta t","E : energie (J)|P : puissance (W)|Delta t : duree (s)"),
(2,"Intensite",r"I=\frac{Q}{\Delta t}","I : intensite (A)|Q : charge (C)|Delta t : duree (s)"),
(2,"Condensateur",r"q=C u","q : charge (C)|C : capacite (F)|u : tension (V)"),
(2,"Constante de temps RC",r"\tau=R C","tau : constante de temps (s)|R : resistance (Ohm)|C : capacite (F)"),
(3,"Frequence",r"f=\frac{1}{T}","f : frequence (Hz)|T : periode (s)"),
(3,"Longueur d'onde",r"\lambda=v T=\frac{v}{f}","lambda : longueur d'onde (m)|v : celerite (m/s)|T : periode (s)  f : frequence (Hz)"),
(3,"Energie d'un photon",r"E=h\nu=\frac{h c}{\lambda}","E : energie (J)  nu : frequence (Hz)|h = 6,63.10^-34 J.s|c = 3,00.10^8 m/s"),
(3,"Indice de refraction",r"n=\frac{c}{v}","n : indice (sans unite)|c : vitesse de la lumiere dans le vide|v : vitesse dans le milieu"),
(3,"Snell-Descartes",r"n_1 sin i_1=n_2 sin i_2","n1, n2 : indices des milieux|i1 : angle d'incidence|i2 : angle de refraction"),
(3,"Conjugaison",r"\frac{1}{OA'}-\frac{1}{OA}=\frac{1}{f'}","OA, OA' : positions objet / image (m)|f' : distance focale (m)"),
(3,"Grandissement",r"\gamma=\frac{A'B'}{AB}=\frac{OA'}{OA}","gamma : grandissement (sans unite)|AB : objet  A'B' : image"),
(3,"Niveau d'intensite sonore",r"L=10 log\frac{I}{I_0}","L : niveau (dB)|I : intensite sonore (W/m2)|I0 = 1,0.10^-12 W/m2"),
(4,"Quantite de matiere",r"n=\frac{m}{M}","n : quantite de matiere (mol)|m : masse (g)|M : masse molaire (g/mol)"),
(4,"Nombre d'entites",r"N=n\times N_A","N : nombre d'entites|n : quantite de matiere (mol)|NA = 6,02.10^23 /mol"),
(4,"Concentration molaire",r"C=\frac{n}{V}","C : concentration (mol/L)|n : quantite de matiere (mol)|V : volume (L)"),
(4,"Concentration massique",r"C_m=\frac{m}{V}","Cm : concentration massique (g/L)|m : masse (g)|V : volume (L)"),
(4,"Dilution",r"C_1 V_1=C_2 V_2","C1, V1 : solution mere|C2, V2 : solution fille"),
(4,"Volume molaire",r"n=\frac{V}{V_m}","V : volume du gaz (L)|Vm = 24 L/mol a 20 C"),
(4,"Gaz parfait",r"P V=n R T","P : pression (Pa)  V : volume (m3)|n : (mol)  T : temperature (K)|R = 8,314 J/mol/K"),
(4,"pH",r"pH=-log[H_3O^+]","[H3O+] en mol/L|pH < 7 : acide   pH > 7 : basique"),
(4,"Beer-Lambert",r"A=\epsilon l C","A : absorbance (sans unite)|l : largeur de cuve (cm)|C : concentration (mol/L)"),
(4,"Equivalence d'un titrage",r"C_A V_A=C_B V_E","Pour une reaction mole a mole|VE : volume a l'equivalence"),
(4,"Rendement d'une synthese",r"\eta=\frac{n_{exp}}{n_{max}}","eta : rendement (sans unite)|n exp : quantite obtenue|n max : quantite theorique"),
]
